version: '3'
services:
  frontend:
    # platform: linux/x86_64
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    restart: always

volumes:
  db_data: