import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  colorStatus: "light",
};

export const appSlice = createSlice({
  name: 'counter',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {

    changeColorState: (state) =>{
        state.colorStatus = state.colorStatus === "dark" ? "light" : "dark";
    }

  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
  },
});

export const { changeColorState } = appSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const getcolorState = (state) => state.colorState.colorStatus;


export default appSlice.reducer;
